- name: "Disable Intel NID {{ channel.nid }}: {{ channel.descrip }}"
  ansible.builtin.blockinfile:
    path: "{{ device_hints_path }}"
    # NOTE: "as=0" (i.e. "association") sets the NID to 'disabled'
    # See documentation in https://www.freebsd.org/cgi/man.cgi?query=snd_hda
    block: "hint.hdaa.{{ channel.card }}.nid{{ channel.nid }}.config=\"as=0\""
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ channel.descrip }}"
    state: present
    create: false
  become: true
  become_user: root

